// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgysbkcnurckopsjqsmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpneXNia2NudXJja29wc2pxc21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzA2OTQsImV4cCI6MjA3MDUwNjY5NH0.cMfhysx7-DnQYOIMHtUxlf-D8T6HVqecAJaDgsA2Uco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});